# Use Segger's RTT unless another stdio_% is already used
ifeq (,$(filter stdio_% slipdev_stdio,$(USEMODULE)))
  USEMODULE += stdio_rtt
endif

USEMODULE += cst816s

ifneq (,$(filter disp_dev,$(USEMODULE)))
  USEMODULE += lpm013m126
endif

ifneq (,$(filter mtd,$(USEMODULE)))
  USEMODULE += mtd_spi_nor
endif

# default to using littlefs2 on the external flash
ifneq (,$(filter vfs_default,$(USEMODULE)))
  USEPKG += littlefs2
  USEMODULE += mtd
endif

# include common nrf52 dependencies
include $(RIOTBOARD)/common/nrf52/Makefile.dep
